package tail

// Property-based tests generated by the property-test-generator skill.
//
// These live in package tail (not tail_test) because every target is
// unexported: matchLumberjackCompressed, cursorFile/cursorVersion, and
// cloneRawMessage. Stdlib only — testing/quick for structured values and
// go test -fuzz for the string-input no-panic property.
//
// Targets and properties:
//   1. matchLumberjackCompressed — reference oracle, metamorphic, no-panic
//   2. cursorFile JSON envelope  — roundtrip, metamorphic wire-shape
//   3. cloneRawMessage           — value-equality, non-aliasing

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"math/rand"
	"reflect"
	"strconv"
	"strings"
	"testing"
	"testing/quick"
	"time"
)

// ---------------------------------------------------------------------------
// Shared generators / helpers
// ---------------------------------------------------------------------------

const alnum = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

func randAlnum(r *rand.Rand, n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = alnum[r.Intn(len(alnum))]
	}
	return string(b)
}

// ljLayout mirrors the lumberjack backup timestamp layout used by the
// production code's documented format <prefix><19-char-ts><ext>.
const ljLayout = "2006-01-02T15-04-05"

// validLumberjackTS returns a 19-character timestamp parseable by ljLayout.
// Seconds are bounded to 1970..~2100 so the year is always 4 digits (19 chars).
func validLumberjackTS(r *rand.Rand) string {
	sec := r.Int63n(4102444800)
	return time.Unix(sec, 0).UTC().Format(ljLayout)
}

// mutateTS flips one character of a timestamp so it usually no longer parses
// while keeping the 19-character length.
func mutateTS(ts string, r *rand.Rand) string {
	b := []byte(ts)
	b[r.Intn(len(b))] = alnum[r.Intn(len(alnum))]
	return string(b)
}

func randPrefix(r *rand.Rand) string {
	return randAlnum(r, 1+r.Intn(6)) + "-"
}

func randExt(r *rand.Rand) string {
	switch r.Intn(3) {
	case 0:
		return ""
	case 1:
		return ".log"
	default:
		return "." + randAlnum(r, 1+r.Intn(4))
	}
}

// differentSameLen returns an alphanumeric string the same length as ref but
// not equal to it. ref always ends in "-" (a non-alnum byte), so a single draw
// already differs.
func differentSameLen(r *rand.Rand, ref string) string {
	if ref == "" {
		return ref
	}
	for {
		if s := randAlnum(r, len(ref)); s != ref {
			return s
		}
	}
}

// slowMatchCompressed is the obviously-correct reference for
// matchLumberjackCompressed, derived from the documented contract:
// n is a match iff n == prefix + <19-char ts parseable by ljLayout> + ext + ".gz".
// It is intentionally written without consulting the implementation.
func slowMatchCompressed(n, prefix, ext string) bool {
	body, ok := strings.CutSuffix(n, ".gz")
	if !ok {
		return false
	}
	body, ok = strings.CutSuffix(body, ext) // CutSuffix(x, "") == (x, true)
	if !ok {
		return false
	}
	mid, ok := strings.CutPrefix(body, prefix)
	if !ok {
		return false
	}
	if len(mid) != 19 {
		return false
	}
	_, err := time.Parse(ljLayout, mid)
	return err == nil
}

// ---------------------------------------------------------------------------
// TARGET 1: matchLumberjackCompressed
// ---------------------------------------------------------------------------

// ljInDomainCase generates inputs where n always begins with prefix — the
// domain the production caller guarantees (lumberjackSource.Enumerate filters
// with strings.HasPrefix before calling). This isolates the timestamp / ext /
// length / ".gz" logic from the prefix-content question.
type ljInDomainCase struct{ N, Prefix, Ext string }

func (ljInDomainCase) Generate(r *rand.Rand, _ int) reflect.Value {
	prefix := randPrefix(r)
	ext := randExt(r)
	var mid string
	switch r.Intn(4) {
	case 0:
		mid = validLumberjackTS(r) // valid 19-char timestamp
	case 1:
		mid = mutateTS(validLumberjackTS(r), r) // 19-char, usually invalid
	case 2:
		mid = randAlnum(r, r.Intn(25)) // arbitrary length
	default:
		mid = validLumberjackTS(r)[:r.Intn(20)] // wrong-length truncation
	}
	n := prefix + mid + ext
	if r.Intn(3) != 0 { // usually append ".gz"
		n += ".gz"
	}
	return reflect.ValueOf(ljInDomainCase{N: n, Prefix: prefix, Ext: ext})
}

// TestProperty_ReferenceOracle_matchLumberjackCompressed checks the
// implementation against slowMatchCompressed over the caller-guaranteed domain
// (n begins with prefix). Expected to pass: it certifies the ".gz"/ext/length/
// timestamp branches.
func TestProperty_ReferenceOracle_matchLumberjackCompressed(t *testing.T) {
	prop := func(c ljInDomainCase) bool {
		return matchLumberjackCompressed(c.N, c.Prefix, c.Ext) ==
			slowMatchCompressed(c.N, c.Prefix, c.Ext)
	}
	if err := quick.Check(prop, &quick.Config{MaxCount: 5000}); err != nil {
		t.Fatal(err)
	}
}

// ljDocContractCase generates inputs that match the structural shape of a
// compressed backup but whose leading run is sometimes a *different* string of
// the same length as prefix. The documented contract says n must START WITH
// prefix; this probes whether the implementation actually verifies that.
type ljDocContractCase struct{ N, Prefix, Ext string }

func (ljDocContractCase) Generate(r *rand.Rand, _ int) reflect.Value {
	prefix := randPrefix(r)
	ext := randExt(r)
	ts := validLumberjackTS(r)
	leading := prefix
	if r.Intn(2) == 0 {
		leading = differentSameLen(r, prefix) // same length, different content
	}
	n := leading + ts + ext + ".gz"
	return reflect.ValueOf(ljDocContractCase{N: n, Prefix: prefix, Ext: ext})
}

// TestProperty_DocumentedContractOracle_matchLumberjackCompressed asserts the
// documented contract: a name is a compressed backup only if it BEGINS WITH
// prefix. slowMatchCompressed enforces that; the implementation is checked
// against it for well-formed-but-wrong-prefix names. matchLumberjackCompressed
// verifies the prefix itself (not just its length), so a same-length leading
// run with a valid timestamp/ext/".gz" no longer spuriously matches.
func TestProperty_DocumentedContractOracle_matchLumberjackCompressed(t *testing.T) {
	prop := func(c ljDocContractCase) bool {
		return matchLumberjackCompressed(c.N, c.Prefix, c.Ext) ==
			slowMatchCompressed(c.N, c.Prefix, c.Ext)
	}
	if err := quick.Check(prop, &quick.Config{MaxCount: 5000}); err != nil {
		t.Fatal(err)
	}
}

// ljPositive generates a (prefix, ext, validTS) triple for the metamorphic
// construction property.
type ljPositive struct {
	Prefix, Ext, TS string
}

func (ljPositive) Generate(r *rand.Rand, _ int) reflect.Value {
	return reflect.ValueOf(ljPositive{
		Prefix: randPrefix(r),
		Ext:    randExt(r),
		TS:     validLumberjackTS(r),
	})
}

// TestProperty_Metamorphic_matchLumberjackCompressed checks two construction
// relations that hold independent of the reference oracle:
//   - a canonical compressed name (prefix+ts+ext+".gz") must be recognised;
//   - the same name without the ".gz" suffix must not be.
func TestProperty_Metamorphic_matchLumberjackCompressed(t *testing.T) {
	prop := func(c ljPositive) bool {
		withGz := c.Prefix + c.TS + c.Ext + ".gz"
		if !matchLumberjackCompressed(withGz, c.Prefix, c.Ext) {
			return false
		}
		noGz := c.Prefix + c.TS + c.Ext
		return !matchLumberjackCompressed(noGz, c.Prefix, c.Ext)
	}
	if err := quick.Check(prop, &quick.Config{MaxCount: 5000}); err != nil {
		t.Fatal(err)
	}
}

// FuzzProperty_NoPanic_matchLumberjackCompressed asserts the function never
// panics on arbitrary string inputs, and that within the caller-guaranteed
// domain (n begins with prefix) it agrees with the reference oracle.
func FuzzProperty_NoPanic_matchLumberjackCompressed(f *testing.F) {
	f.Add("events-2024-01-02T03-04-05.log.gz", "events-", ".log")
	f.Add("events-2024-01-02T03-04-05.log", "events-", ".log")
	f.Add("x.gz", "", "")
	f.Add("", "", "")
	f.Add("app-not-a-timestamp.gz", "app-", "")

	f.Fuzz(func(t *testing.T, n, prefix, ext string) {
		got := matchLumberjackCompressed(n, prefix, ext) // must not panic
		if strings.HasPrefix(n, prefix) {
			if want := slowMatchCompressed(n, prefix, ext); got != want {
				t.Fatalf("in-domain divergence: matchLumberjackCompressed(%q,%q,%q)=%v, oracle=%v",
					n, prefix, ext, got, want)
			}
		}
	})
}

// ---------------------------------------------------------------------------
// TARGET 2: cursorFile JSON envelope
// ---------------------------------------------------------------------------

func randUint64(r *rand.Rand) uint64 {
	switch r.Intn(5) {
	case 0:
		return 0
	case 1:
		return 1
	case 2:
		return math.MaxUint64
	case 3:
		return uint64(r.Int63())
	default:
		return r.Uint64()
	}
}

func randInt64(r *rand.Rand) int64 {
	switch r.Intn(6) {
	case 0:
		return 0
	case 1:
		return -1
	case 2:
		return math.MaxInt64
	case 3:
		return math.MinInt64
	case 4:
		return r.Int63()
	default:
		return -r.Int63()
	}
}

// randFileName produces a valid-UTF-8 path string (possibly empty) including
// ASCII specials and multi-byte runes. Standard JSON string (un)marshalling
// round-trips all of these byte-for-byte.
func randFileName(r *rand.Rand) string {
	rs := make([]rune, r.Intn(20))
	for i := range rs {
		rs[i] = rune(r.Intn(0x300) + 0x20) // 0x20..0x31f: valid, no surrogates
	}
	return string(rs)
}

// randMeta returns either nil or a *compact* valid-JSON value with no
// HTML-special characters. Compactness matters: encoding/json compacts a
// json.RawMessage on marshal, so only already-compact values round-trip
// byte-for-byte — staying inside that domain keeps the property about gotail's
// envelope rather than encoding/json's whitespace handling.
func randMeta(r *rand.Rand) json.RawMessage {
	switch r.Intn(7) {
	case 0:
		return nil
	case 1:
		return json.RawMessage(strconv.FormatInt(randInt64(r), 10))
	case 2:
		return json.RawMessage(`"` + randAlnum(r, r.Intn(8)) + `"`)
	case 3:
		return json.RawMessage("true")
	case 4:
		return json.RawMessage("false")
	case 5:
		return json.RawMessage("null")
	default:
		return json.RawMessage(fmt.Sprintf(`{"k":%d}`, r.Intn(1000)))
	}
}

// cursorFileCase wraps a cursorFile in the current schema (Version == 1) with
// extreme Inode/Offset values and compact Meta — the in-domain inputs for the
// envelope roundtrip.
type cursorFileCase struct{ cf cursorFile }

func (cursorFileCase) Generate(r *rand.Rand, _ int) reflect.Value {
	cf := cursorFile{
		Pos: Position{
			File:   randFileName(r),
			Inode:  randUint64(r),
			Offset: randInt64(r),
		},
		Meta:    randMeta(r),
		Version: cursorVersion,
	}
	return reflect.ValueOf(cursorFileCase{cf: cf})
}

// TestProperty_Roundtrip_CursorEnvelope checks that marshalling a cursorFile
// and unmarshalling it back preserves the position exactly, the version, and
// the meta bytes. The high-value stress is the full uint64/int64 range against
// Position's `,string` json tags.
func TestProperty_Roundtrip_CursorEnvelope(t *testing.T) {
	prop := func(c cursorFileCase) bool {
		data, err := json.Marshal(c.cf)
		if err != nil {
			t.Logf("marshal failed (out of domain): %v", err)
			return false
		}
		var out cursorFile
		if err := json.Unmarshal(data, &out); err != nil {
			t.Logf("unmarshal failed: %v\njson=%s", err, data)
			return false
		}
		if out.Pos != c.cf.Pos {
			return false
		}
		if out.Version != c.cf.Version {
			return false
		}
		// Meta is omitempty: nil and empty both serialize away and reload as nil.
		if len(c.cf.Meta) == 0 {
			return len(out.Meta) == 0
		}
		return bytes.Equal(out.Meta, c.cf.Meta)
	}
	if err := quick.Check(prop, &quick.Config{MaxCount: 3000}); err != nil {
		t.Fatal(err)
	}
}

// TestProperty_Metamorphic_CursorEnvelopeWireShape checks the on-disk shape:
// Inode and Offset must serialize as quoted strings (the `,string` tag), the
// version is always present, and the meta key appears iff Meta is non-empty.
func TestProperty_Metamorphic_CursorEnvelopeWireShape(t *testing.T) {
	prop := func(c cursorFileCase) bool {
		data, err := json.Marshal(c.cf)
		if err != nil {
			return false
		}
		s := string(data)
		if !strings.Contains(s, fmt.Sprintf(`"inode":"%d"`, c.cf.Pos.Inode)) {
			return false
		}
		if !strings.Contains(s, fmt.Sprintf(`"offset":"%d"`, c.cf.Pos.Offset)) {
			return false
		}
		if !strings.Contains(s, `"version":1`) {
			return false
		}
		hasMeta := strings.Contains(s, `"meta":`)
		// Bug iff presence equals emptiness (present-when-empty or absent-when-set).
		return hasMeta != (len(c.cf.Meta) == 0)
	}
	if err := quick.Check(prop, &quick.Config{MaxCount: 3000}); err != nil {
		t.Fatal(err)
	}
}

// ---------------------------------------------------------------------------
// TARGET 3: cloneRawMessage
// ---------------------------------------------------------------------------

// TestProperty_ValueEquality_cloneRawMessage checks that a clone has the same
// bytes as its input for all inputs, and that nil round-trips to nil.
func TestProperty_ValueEquality_cloneRawMessage(t *testing.T) {
	prop := func(b []byte) bool {
		return bytes.Equal(cloneRawMessage(b), b)
	}
	if err := quick.Check(prop, &quick.Config{MaxCount: 2000}); err != nil {
		t.Fatal(err)
	}
	if got := cloneRawMessage(nil); got != nil {
		t.Fatalf("cloneRawMessage(nil) = %v, want nil", got)
	}
}

// TestProperty_NoAliasing_cloneRawMessage checks the defensive-copy contract:
// the clone must not share a backing array with the input, so mutating the
// clone leaves the input untouched.
func TestProperty_NoAliasing_cloneRawMessage(t *testing.T) {
	prop := func(b []byte) bool {
		if len(b) == 0 {
			return true // no element to alias
		}
		c := cloneRawMessage(b)
		if !bytes.Equal(c, b) {
			return false
		}
		before := b[0]
		c[0] = ^c[0] // mutate the clone
		return b[0] == before
	}
	if err := quick.Check(prop, &quick.Config{MaxCount: 2000}); err != nil {
		t.Fatal(err)
	}
}
