package forward

// Property-based tests generated by the property-test-generator skill.
// Spec source: docs/design.md (backoff jitter, §"best-in-class" item 6) plus
// the documented contracts on jitteredBackoff, IdentityDecoderCopy, and
// JSONDecoder. These tests are intentionally read-only on the implementation:
// a failure should be inspected and fixed by hand, not papered over here.

import (
	"bytes"
	"encoding/json"
	"math/rand"
	"reflect"
	"testing"
	"testing/quick"
	"time"
)

// quickConfig is the shared iteration budget. The cookbook's minimum standard
// is 1000 iterations for testing/quick — 100 (the stdlib default) is too few
// to reach boundary classes.
var quickConfig = &quick.Config{MaxCount: 1000}

// ---------------------------------------------------------------------------
// jitteredBackoff
// ---------------------------------------------------------------------------

// backoffCase carries a valid Forwarder backoff configuration plus an attempt
// number. New() guarantees InitialBackoff>0, MaxBackoff>0, BackoffJitter∈[0,1],
// so the generator only produces values inside those validated bounds.
type backoffCase struct {
	initial time.Duration
	max     time.Duration
	jitter  float64
	attempt int
}

func (backoffCase) Generate(r *rand.Rand, _ int) reflect.Value {
	return reflect.ValueOf(backoffCase{
		initial: time.Duration(1 + r.Int63n(int64(time.Second))),
		max:     time.Duration(1 + r.Int63n(int64(time.Minute))),
		jitter:  r.Float64(),
		// 0..127 reaches both the small-attempt exponential region and the
		// saturated region where the ceiling pins to MaxBackoff.
		attempt: r.Intn(128),
	})
}

func (c backoffCase) fwd() *Forwarder[[]byte] {
	return &Forwarder[[]byte]{opts: Options[[]byte]{
		InitialBackoff: c.initial,
		MaxBackoff:     c.max,
		BackoffJitter:  c.jitter,
	}}
}

// detBackoffCase is the deterministic variant: BackoffJitter is implicitly 0,
// so jitteredBackoff is documented to "always return ceiling". Properties that
// require a stable, repeatable value (determinism, monotonicity) use this.
type detBackoffCase struct {
	initial time.Duration
	max     time.Duration
	attempt int
}

func (detBackoffCase) Generate(r *rand.Rand, _ int) reflect.Value {
	return reflect.ValueOf(detBackoffCase{
		initial: time.Duration(1 + r.Int63n(int64(time.Second))),
		max:     time.Duration(1 + r.Int63n(int64(time.Minute))),
		attempt: r.Intn(128),
	})
}

func (c detBackoffCase) fwd() *Forwarder[[]byte] {
	return &Forwarder[[]byte]{opts: Options[[]byte]{
		InitialBackoff: c.initial,
		MaxBackoff:     c.max,
		BackoffJitter:  0,
	}}
}

// Property: bounds/preservation — the result is always in [0, MaxBackoff].
// The ceiling never exceeds MaxBackoff and the jitter window sits below the
// ceiling, so the duration can never be negative nor exceed the cap.
func TestProperty_Bounds_jitteredBackoff(t *testing.T) {
	prop := func(c backoffCase) bool {
		d := c.fwd().jitteredBackoff(c.attempt)
		return d >= 0 && d <= c.max
	}
	if err := quick.Check(prop, quickConfig); err != nil {
		t.Fatal(err)
	}
}

// Property: no-panic/totality — large attempt counts must not panic or overflow.
// jitteredBackoff shifts InitialBackoff left by attempt; without the documented
// shift clamp this overflows. Exercise both random and adversarial extremes.
func TestProperty_NoPanic_jitteredBackoff(t *testing.T) {
	prop := func(c backoffCase) bool {
		_ = c.fwd().jitteredBackoff(c.attempt)
		return true
	}
	if err := quick.Check(prop, quickConfig); err != nil {
		t.Fatal(err)
	}

	// Explicit extremes around the documented shift clamp (62) and beyond.
	f := &Forwarder[[]byte]{opts: Options[[]byte]{
		InitialBackoff: 100 * time.Millisecond,
		MaxBackoff:     30 * time.Second,
		BackoffJitter:  0.2,
	}}
	for _, attempt := range []int{0, 1, 61, 62, 63, 64, 1_000, 1_000_000, int(^uint(0) >> 1)} {
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("jitteredBackoff panicked at attempt=%d: %v", attempt, r)
				}
			}()
			d := f.jitteredBackoff(attempt)
			if d < 0 || d > f.opts.MaxBackoff {
				t.Fatalf("attempt=%d: out of bounds d=%v (max=%v)", attempt, d, f.opts.MaxBackoff)
			}
		}()
	}
}

// Property: determinism — with BackoffJitter==0 the duration is documented to
// always equal the ceiling, so repeated calls for the same attempt are equal.
func TestProperty_Determinism_jitteredBackoff(t *testing.T) {
	prop := func(c detBackoffCase) bool {
		f := c.fwd()
		first := f.jitteredBackoff(c.attempt)
		for range 4 {
			if f.jitteredBackoff(c.attempt) != first {
				return false
			}
		}
		return true
	}
	if err := quick.Check(prop, quickConfig); err != nil {
		t.Fatal(err)
	}
}

// Property: monotonicity — with BackoffJitter==0 (deterministic ceiling) the
// backoff is non-decreasing in attempt: doubling up to the MaxBackoff cap.
func TestProperty_Monotonicity_jitteredBackoff(t *testing.T) {
	prop := func(c detBackoffCase) bool {
		f := c.fwd()
		return f.jitteredBackoff(c.attempt) <= f.jitteredBackoff(c.attempt+1)
	}
	if err := quick.Check(prop, quickConfig); err != nil {
		t.Fatal(err)
	}
}

// ---------------------------------------------------------------------------
// IdentityDecoderCopy
// ---------------------------------------------------------------------------

// Property: reference oracle — the copy must equal the input byte-for-byte and
// never error. The trivially-correct reference is "output == input".
func FuzzProperty_Oracle_IdentityDecoderCopy(f *testing.F) {
	f.Add([]byte(nil))
	f.Add([]byte{})
	f.Add([]byte{0})
	f.Add([]byte("hello"))
	f.Add([]byte("\x00\x01\xff\xfe"))

	f.Fuzz(func(t *testing.T, line []byte) {
		out, err := IdentityDecoderCopy(line)
		if err != nil {
			t.Fatalf("unexpected error for input %q: %v", line, err)
		}
		if !bytes.Equal(out, line) {
			t.Fatalf("content mismatch\ninput = %q\nout   = %q", line, out)
		}
	})
}

// Property: non-aliasing (the function's reason for existing) — the returned
// slice must not share backing storage with the input, because the Forwarder
// feeds it a reused read buffer that later gets overwritten. Mutating the input
// after the call must leave the copy unchanged.
func FuzzProperty_NonAliasing_IdentityDecoderCopy(f *testing.F) {
	f.Add([]byte{0})
	f.Add([]byte("hello"))
	f.Add([]byte("\x00\x01\xff\xfe"))

	f.Fuzz(func(t *testing.T, line []byte) {
		if len(line) == 0 {
			return // nothing to overwrite; aliasing is undefined for empty input
		}
		out, err := IdentityDecoderCopy(line)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		snapshot := append([]byte(nil), out...)
		for i := range line {
			line[i] ^= 0xFF // clobber every byte of the input buffer
		}
		if !bytes.Equal(out, snapshot) {
			t.Fatalf("copy aliases input: mutating input changed the copy\nbefore = %q\nafter  = %q", snapshot, out)
		}
	})
}

// ---------------------------------------------------------------------------
// JSONDecoder
// ---------------------------------------------------------------------------

// jsonTarget is a concrete instantiation of T for the generic JSONDecoder.
type jsonTarget struct {
	Name   string
	Count  int
	Tags   []string
	Active bool
}

// Generate produces JSON-roundtrippable values: strings are restricted to
// printable ASCII so encoding/json's lossy invalid-UTF-8 replacement (which is
// a property of the standard library, not the decoder) can't cause a spurious
// roundtrip failure.
func (jsonTarget) Generate(r *rand.Rand, size int) reflect.Value {
	str := func() string {
		n := r.Intn(size + 1)
		b := make([]byte, n)
		for i := range b {
			b[i] = byte(0x20 + r.Intn(0x5F)) // printable ASCII
		}
		return string(b)
	}
	tags := make([]string, r.Intn(5))
	for i := range tags {
		tags[i] = str()
	}
	return reflect.ValueOf(jsonTarget{
		Name:   str(),
		Count:  r.Int(),
		Tags:   tags,
		Active: r.Intn(2) == 1,
	})
}

// Property: reference oracle — JSONDecoder[T]() must behave identically to a
// direct json.Unmarshal into a T: same error presence, same decoded value.
func FuzzProperty_Oracle_JSONDecoder(f *testing.F) {
	f.Add([]byte(`{"Name":"x","Count":3,"Tags":["a"],"Active":true}`))
	f.Add([]byte(`{}`))
	f.Add([]byte(``))
	f.Add([]byte(`not json`))
	f.Add([]byte(`{"Count": 9999999999999999999999}`))
	f.Add([]byte("\x00\x01\xff"))

	dec := JSONDecoder[jsonTarget]()
	f.Fuzz(func(t *testing.T, line []byte) {
		got, gotErr := dec(line)

		var want jsonTarget
		wantErr := json.Unmarshal(line, &want)

		if (gotErr != nil) != (wantErr != nil) {
			t.Fatalf("error mismatch for %q: decoder err=%v, json.Unmarshal err=%v", line, gotErr, wantErr)
		}
		if gotErr == nil && !reflect.DeepEqual(got, want) {
			t.Fatalf("value mismatch for %q:\ndecoder = %+v\noracle  = %+v", line, got, want)
		}
	})
}

// Property: no-panic/totality — arbitrary bytes must yield a value or a non-nil
// error, never a panic. Uses map[string]any to exercise a different decode path
// from the struct oracle above.
func FuzzProperty_NoPanic_JSONDecoder(f *testing.F) {
	f.Add([]byte(``))
	f.Add([]byte(`{`))
	f.Add([]byte(`[[[[[[[[[[`))
	f.Add([]byte("\x00\xff\xfe"))

	dec := JSONDecoder[map[string]any]()
	f.Fuzz(func(t *testing.T, line []byte) {
		_, _ = dec(line) // any return is acceptable; we require non-panic
	})
}

// Property: roundtrip — for a JSON-roundtrippable T, marshalling a value then
// decoding the bytes recovers an equal value.
func TestProperty_Roundtrip_JSONDecoder(t *testing.T) {
	dec := JSONDecoder[jsonTarget]()
	prop := func(x jsonTarget) bool {
		b, err := json.Marshal(x)
		if err != nil {
			return false
		}
		got, err := dec(b)
		if err != nil {
			return false
		}
		return reflect.DeepEqual(got, x)
	}
	if err := quick.Check(prop, quickConfig); err != nil {
		t.Fatal(err)
	}
}
