package watch_test

// Property-based tests for watch.LineReader's line-framing transformation.
//
// These were generated by the property-test-generator skill. They go beyond
// the existing FuzzLineReader (which pins one byte-conservation property with
// KeepNewline=false) by adding an independent reference oracle, position
// monotonicity, totality, and ErrLineTooLong-recovery checks. They drive a
// real pollWatcher over a temp file, exactly as production code does, then
// treat "input bytes on disk -> sequence of (line, pos)" as the observable
// transformation.
//
// Properties are NOT auto-fixed: if one fails, the implementation is the
// suspect, not the test.

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"slices"
	"testing"
	"time"

	"github.com/jacobcase/gotail/v3/watch"
)

// maxPropInput bounds fuzz input size so each iteration stays fast (the driver
// writes the file in chunks of one byte in the worst case) and so the
// large-MaxLine oracle does not grow the buffer to multi-megabyte sizes.
const maxPropInput = 1 << 13 // 8 KiB

// lrEvent is one observation from a LineReader.Next call: either a yielded line
// (tooLong == false, line holds a copy) or a recoverable ErrLineTooLong event.
type lrEvent struct {
	line    []byte
	offset  int64
	tooLong bool
}

// driveLR writes input to a temp file in chunks of size chunk, then drains a
// LineReader to a terminal condition, returning every observation in order.
// Lines are slices.Clone'd at yield time because the returned slice aliases the
// reader's internal buffer and is invalidated by the next Next call.
func driveLR(t *testing.T, input []byte, chunk int, opts watch.LineOptions) (events []lrEvent, terminal error) {
	t.Helper()
	if chunk <= 0 {
		chunk = 1
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "prop.log")
	f, err := os.Create(path)
	if err != nil {
		t.Fatalf("create: %v", err)
	}
	for i := 0; i < len(input); i += chunk {
		end := min(i+chunk, len(input))
		if _, err := f.Write(input[i:end]); err != nil {
			t.Fatalf("write: %v", err)
		}
	}
	f.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	w, err := watch.NewPolling(watch.Config{
		Path:      path,
		Interval:  time.Millisecond,
		Whence:    io.SeekStart,
		StopAtEOF: true,
	})
	if err != nil {
		t.Fatalf("NewPolling: %v", err)
	}
	lr := watch.NewLineReader(w, opts)
	defer lr.Close()

	for {
		line, pos, err := lr.Next(ctx)
		switch {
		case err == nil:
			events = append(events, lrEvent{line: slices.Clone(line), offset: pos.Offset})
		case errors.Is(err, watch.ErrLineTooLong):
			events = append(events, lrEvent{tooLong: true, offset: pos.Offset})
		default:
			return events, err // io.EOF or a context error
		}
	}
}

// refLines is a deliberately naive reference framer: split on '\n', keep only
// complete (newline-terminated) lines, always strip exactly one trailing '\r'
// (CRLF normalization, per design.md:1095 and TestLineReader_CRLF), and append
// '\n' only when keepNewline is set. Any trailing partial line is dropped, as a
// StopAtEOF reader does. This is the oracle the optimized buffered/refill/grow
// path is checked against.
func refLines(input []byte, keepNewline bool) [][]byte {
	var out [][]byte
	rest := input
	for {
		i := bytes.IndexByte(rest, '\n')
		if i < 0 {
			break
		}
		content := bytes.TrimSuffix(rest[:i], []byte{'\r'})
		if keepNewline {
			out = append(out, append(slices.Clone(content), '\n'))
		} else {
			out = append(out, slices.Clone(content))
		}
		rest = rest[i+1:]
	}
	return out
}

// newlineOffsets returns, for each '\n' in input, the byte offset just past it.
// These are the positions a byte-resolution LineReader must report after each
// yielded line (design.md:36, design.md:1006: Offset += idx+1).
func newlineOffsets(input []byte) []int64 {
	var offs []int64
	for i, b := range input {
		if b == '\n' {
			offs = append(offs, int64(i)+1)
		}
	}
	return offs
}

// FuzzProperty_ReferenceOracle_LineReader — Reference oracle (+ conservation +
// chunk-split metamorphic). The line sequence emitted by LineReader, varying
// chunk size and BufferSize to force refills/growth, must equal refLines for
// both KeepNewline settings. MaxLine is set above the input length so no line
// is ever rejected.
func FuzzProperty_ReferenceOracle_LineReader(f *testing.F) {
	f.Add([]byte("hello\nworld\n"), uint8(16), uint8(8), false)
	f.Add([]byte("a\r\nb\r\n"), uint8(1), uint8(2), true)
	f.Add([]byte("\n\n\n"), uint8(3), uint8(1), false)
	f.Add([]byte("no trailing newline"), uint8(4), uint8(64), true)
	f.Add([]byte("trailing cr\rkept\n"), uint8(5), uint8(3), false)

	f.Fuzz(func(t *testing.T, input []byte, chunk, bufSize uint8, keepNL bool) {
		if len(input) > maxPropInput {
			return
		}
		opts := watch.LineOptions{
			BufferSize:  int(bufSize),
			MaxLine:     len(input) + 1, // never too long
			KeepNewline: keepNL,
		}
		events, terminal := driveLR(t, input, int(chunk), opts)
		if !errors.Is(terminal, io.EOF) {
			return // context deadline under load; not a correctness failure
		}

		want := refLines(input, keepNL)
		if len(events) != len(want) {
			t.Fatalf("yielded %d lines, oracle says %d\ninput=%q keepNL=%v chunk=%d buf=%d",
				len(events), len(want), input, keepNL, chunk, bufSize)
		}
		for i, ev := range events {
			if ev.tooLong {
				t.Fatalf("unexpected ErrLineTooLong at line %d with MaxLine>len(input)", i)
			}
			if !bytes.Equal(ev.line, want[i]) {
				t.Fatalf("line %d = %q, oracle says %q\ninput=%q keepNL=%v chunk=%d buf=%d",
					i, ev.line, want[i], input, keepNL, chunk, bufSize)
			}
		}
	})
}

// FuzzProperty_Monotonicity_LineReader — Monotonicity / preservation. The
// reported Position.Offset after each line must equal the offset just past the
// corresponding '\n' in the input: strictly increasing and advancing by the
// full on-disk consumed byte count (including a stripped '\r'), independent of
// len(line). This catches an offset-vs-returned-length confusion the
// reconstruction-only fuzz cannot.
func FuzzProperty_Monotonicity_LineReader(f *testing.F) {
	f.Add([]byte("ab\ncd\nef\n"), uint8(2), uint8(4), false)
	f.Add([]byte("x\r\ny\r\n"), uint8(1), uint8(1), true)
	f.Add([]byte("\n\n"), uint8(1), uint8(8), false)
	f.Add([]byte("partial tail with no newline"), uint8(3), uint8(16), false)

	f.Fuzz(func(t *testing.T, input []byte, chunk, bufSize uint8, keepNL bool) {
		if len(input) > maxPropInput {
			return
		}
		opts := watch.LineOptions{
			BufferSize:  int(bufSize),
			MaxLine:     len(input) + 1,
			KeepNewline: keepNL,
		}
		events, terminal := driveLR(t, input, int(chunk), opts)
		if !errors.Is(terminal, io.EOF) {
			return
		}

		want := newlineOffsets(input)
		if len(events) != len(want) {
			t.Fatalf("yielded %d positions, expected %d\ninput=%q chunk=%d buf=%d",
				len(events), len(want), input, chunk, bufSize)
		}
		var prev int64
		for i, ev := range events {
			if ev.offset != want[i] {
				t.Fatalf("position %d = %d, want %d (just past '\\n')\ninput=%q chunk=%d buf=%d",
					i, ev.offset, want[i], input, chunk, bufSize)
			}
			if ev.offset <= prev && i > 0 {
				t.Fatalf("position not strictly increasing: %d after %d\ninput=%q", ev.offset, prev, input)
			}
			prev = ev.offset
		}
	})
}

// FuzzProperty_Totality_LineReader — No-panic / totality. For any input and any
// BufferSize/MaxLine/chunk combination, draining the reader must terminate at
// io.EOF (small MaxLine exercises the ErrLineTooLong skip path heavily) without
// panicking and without returning any unrecognized terminal error.
func FuzzProperty_Totality_LineReader(f *testing.F) {
	f.Add([]byte("normal\nlines\n"), uint8(8), uint8(16), uint8(4))
	f.Add([]byte("xxxxxxxxxxxxxxxxxxxx\nshort\n"), uint8(3), uint8(2), uint8(1))
	f.Add([]byte{0, 0, '\n', 0xff, '\r', '\n'}, uint8(0), uint8(0), uint8(2))
	f.Add([]byte("no newline at all here"), uint8(1), uint8(1), uint8(1))

	f.Fuzz(func(t *testing.T, input []byte, bufSize, maxLine, chunk uint8) {
		if len(input) > maxPropInput {
			return
		}
		opts := watch.LineOptions{
			BufferSize: int(bufSize),
			MaxLine:    int(maxLine), // 0 -> default 1 MiB; small -> heavy ErrLineTooLong
		}
		_, terminal := driveLR(t, input, int(chunk), opts)
		switch {
		case errors.Is(terminal, io.EOF):
			// expected: file fully drained
		case errors.Is(terminal, context.DeadlineExceeded), errors.Is(terminal, context.Canceled):
			// acceptable: slow iteration under fuzz load, not a correctness bug
		default:
			t.Fatalf("unrecognized terminal error %v\ninput=%q buf=%d maxLine=%d chunk=%d",
				terminal, input, bufSize, maxLine, chunk)
		}
	})
}

// FuzzProperty_ErrLineTooLongRecovery_LineReader — Postcondition / recovery.
// Given short lines surrounding one over-long line, the reader must yield the
// short lines intact, emit ErrLineTooLong exactly once for the over-long line,
// and never re-emit any fragment of the over-long line. The input is
// constructed so component lines stay strictly within (short) or strictly
// beyond (long) MaxLine, avoiding the exact MaxLine boundary.
func FuzzProperty_ErrLineTooLongRecovery_LineReader(f *testing.F) {
	f.Add([]byte("alpha"), []byte("beta"), uint8(16), uint8(4))
	f.Add([]byte(""), []byte("x"), uint8(2), uint8(1))
	f.Add([]byte("ab\rcd"), []byte("ef"), uint8(8), uint8(2))

	f.Fuzz(func(t *testing.T, a, b []byte, maxLine, chunk uint8) {
		ml := int(maxLine)
		if ml < 2 {
			ml = 2
		}
		// Sanitize the short lines: remove framing/CR bytes and keep them
		// strictly shorter than MaxLine so they are never themselves rejected.
		clean := func(s []byte) []byte {
			s = bytes.ReplaceAll(s, []byte{'\n'}, nil)
			s = bytes.ReplaceAll(s, []byte{'\r'}, nil)
			if len(s) > ml-1 {
				s = s[:ml-1]
			}
			return s
		}
		shortA := clean(a)
		shortB := clean(b)
		long := bytes.Repeat([]byte{'x'}, ml+8) // strictly beyond MaxLine

		var input []byte
		input = append(input, shortA...)
		input = append(input, '\n')
		input = append(input, long...)
		input = append(input, '\n')
		input = append(input, shortB...)
		input = append(input, '\n')

		opts := watch.LineOptions{MaxLine: ml}
		events, terminal := driveLR(t, input, int(chunk), opts)
		if !errors.Is(terminal, io.EOF) {
			return
		}

		var lines [][]byte
		tooLong := 0
		for _, ev := range events {
			if ev.tooLong {
				tooLong++
				continue
			}
			lines = append(lines, ev.line)
		}

		if tooLong != 1 {
			t.Fatalf("got %d ErrLineTooLong events, want exactly 1\ninput=%q maxLine=%d", tooLong, input, ml)
		}
		want := [][]byte{shortA, shortB}
		if len(lines) != len(want) {
			t.Fatalf("yielded %d short lines, want 2 (%q, %q)\ninput=%q maxLine=%d",
				len(lines), shortA, shortB, input, ml)
		}
		for i := range want {
			if !bytes.Equal(lines[i], want[i]) {
				t.Fatalf("short line %d = %q, want %q (over-long fragment re-emitted?)\ninput=%q maxLine=%d",
					i, lines[i], want[i], input, ml)
			}
		}
	})
}
